### PR TITLE
Mixins that target the Cards paragraph 

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**
Added different breaking points for Chrome/Safari and Firefox

### CODE REVIEW

**Comment by Ocre42** [comment]
There is still some issues with overflow when resizing the boxes, so we might need to tweak the width values a bit more
usingdatacr
The second issue I'm seeing is that there isn't much use to having this overflow to a single line ellipsis. 
usingdatacr2
The idea of the excerpt is to give an idea as to what we'll find by going to the page on the card, but with a single line we don't get a lot of context. This is just a personal opinion but I'd rather have multi-line ellipsis (which are annoying to implement and might have issues across different browsers), or show empty cards when overflowing.

**Comment by samuele-mattiuzzo** [comment]
@Ocre42 if the problem is the amount of content we show to give an indication over what a card is pointing to, then 1 line with ellipsis is better than an empty box for sure, I will play around with the idea of having a multiline one

For the break point, what browser did you test on?

**Comment by Ocre42** [comment]
@samuele-mattiuzzo  Tested on Chrome

**Comment by sargentfrancesca** [comment]
Can the length of the excerpt be truncated instead in the Django template, if this is causing an issue?: https://docs.djangoproject.com/en/dev/ref/templates/builtins/?from=olddocs#truncatechars

**Comment by samuele-mattiuzzo** [comment]
Adding a multiline breakpoint is fairly hard and requires more hacky solutions than not; I tried some of them but they were not consistent across browsers. I think we can go with the one line solution, as it's a better option than having overlapping text in my opinion.

For what concerns text still overlapping as per @Ocre42's first screenshot, I tried on 2 different devices, screen sizes (15'' retina and 13'') and zoom levels in Chrome, but I don't see it happen anymore. The ellipsis breakpoint for Chrome already kicks in fairly early (1000px) so relaxing that a bit more to a higher value would end up with those boxes truncating sooner on most screens even though it's not required.

We have 2 options:

- we merge this as is and follow up with a second issue, so we can deploy a version that at least doesn't have overlaps

- we postpone deploying this and do some more work on it and deploy it separately

either works and has the same impact, so I'm not leaning towards either in particular

**Comment by sargentfrancesca** [comment]
Ahh, I understand now, ellipsis on breakpoints. It's a tricky one.

I prefer option 1, if we can follow up with a solution soon!

**Comment by samuele-mattiuzzo** [comment]
Another option:

- we always provide in page two versions of the `<p class="standard">` text, one which is the full snippet and the second one `<p class="truncated">` that starts with `display: hidden;` by default and contains a Django-truncated version of the snippet (bearing in mind the ellipsis will be put at an arbitrary point that might still cause overlap, albeit very unlikely)

- once the breakpoint is reached, the two classes will swap `display: block;` and `display: hidden;` so that we show the truncated text and hide the full length one

thoughts @sargentfrancesca @Ocre42 ?

**Pull request merged**
